# Generated by Django 3.1.4 on 2021-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210114_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
