# Generated by Django 3.1.4 on 2021-01-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='roll_out',
            new_name='Make_Public',
        ),
    ]
