# Generated by Django 3.1.4 on 2021-03-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210116_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAnswer',
        ),
    ]
