# Generated by Django 3.1.4 on 2021-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
