# Generated by Django 3.1.4 on 2021-01-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Question',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AssignmentAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=1000)),
                ('ans_file', models.FileField(blank=True, upload_to='Submited_files')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment')),
                ('submited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
