# Generated by Django 3.1.4 on 2021-01-09 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210108_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_date_of_submission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
