# Generated by Django 3.1.4 on 2021-01-09 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_last_date_of_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_date_of_submission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
